import Foundation

enum AppLanguage: String, Codable, CaseIterable, Identifiable, Sendable {
    case system = "system"
    case english = "en"
    case chinese = "zh-Hans"
    case japanese = "ja"
    case korean = "ko"
    case german = "de"
    case french = "fr"
    case spanish = "es"
    case portuguese = "pt"

    var id: String { rawValue }

    var displayName: String {
        displayName(in: .system)
    }

    func displayName(in language: AppLanguage) -> String {
        switch self {
        case .system:
            return L10n.string("settings.language.system", language: language)
        case .english: return "English"
        case .chinese: return "中文"
        case .japanese: return "日本語"
        case .korean: return "한국어"
        case .german: return "Deutsch"
        case .french: return "Français"
        case .spanish: return "Español"
        case .portuguese: return "Português"
        }
    }

    var resolvedLanguage: AppLanguage {
        resolveEffective(preferredLanguages: Locale.preferredLanguages)
    }

    var locale: Locale {
        switch resolvedLanguage {
        case .system: return Locale.current
        case .english: return Locale(identifier: "en_US")
        case .chinese: return Locale(identifier: "zh_Hans_CN")
        case .japanese: return Locale(identifier: "ja_JP")
        case .korean: return Locale(identifier: "ko_KR")
        case .german: return Locale(identifier: "de_DE")
        case .french: return Locale(identifier: "fr_FR")
        case .spanish: return Locale(identifier: "es_ES")
        case .portuguese: return Locale(identifier: "pt_BR")
        }
    }

    func resolveEffective(preferredLanguages: [String] = Locale.preferredLanguages) -> AppLanguage {
        guard self == .system else { return self }
        for identifier in preferredLanguages {
            let lower = identifier.lowercased()
            if lower.hasPrefix("zh") { return .chinese }
            if lower.hasPrefix("ja") { return .japanese }
            if lower.hasPrefix("ko") { return .korean }
            if lower.hasPrefix("de") { return .german }
            if lower.hasPrefix("fr") { return .french }
            if lower.hasPrefix("es") { return .spanish }
            if lower.hasPrefix("pt") { return .portuguese }
            if lower.hasPrefix("en") { return .english }
        }
        return .english
    }

    static func from(stored: String?) -> AppLanguage {
        guard let stored, !stored.isEmpty else { return .system }
        if let exact = AppLanguage(rawValue: stored) {
            return exact
        }
        let lower = stored.lowercased()
        if lower.hasPrefix("zh") { return .chinese }
        if lower.hasPrefix("en") { return .english }
        if lower.hasPrefix("ja") { return .japanese }
        if lower.hasPrefix("ko") { return .korean }
        if lower.hasPrefix("de") { return .german }
        if lower.hasPrefix("fr") { return .french }
        if lower.hasPrefix("es") { return .spanish }
        if lower.hasPrefix("pt") { return .portuguese }
        return .system
    }
}

enum L10n {
    static func string(_ key: String, language: AppLanguage) -> String {
        let resolved = language.resolvedLanguage
        let dict: [String: String]
        switch resolved {
        case .chinese: dict = zh
        case .english: dict = en
        case .japanese: dict = ja
        case .korean: dict = ko
        case .german: dict = de
        case .french: dict = fr
        case .spanish: dict = es
        case .portuguese: dict = pt
        case .system: dict = en
        }
        return dict[key] ?? en[key] ?? zh[key] ?? key
    }

    private static let zh: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor 网络诊断",
        "status.checking": "检查中",
        "status.notChecked": "尚未检查",
        "summary.checking": "正在执行本地网络诊断。",
        "summary.notChecked": "点击“立即检查”开始。",
        "summary.healthy": "网络状态正常，互联网连通性检测通过。",
        "summary.warning": "网络可用，但存在需要关注的信号。",
        "summary.critical": "网络不可用，请检查连接。",
        "quick.path": "路径",
        "quick.activeInterfaces": "活动接口",
        "quick.dns": "DNS",
        "quick.internet": "互联网",
        "quick.notProbed": "未探测",
        "quick.successCount": "%d/%d 成功",
        "quick.checkNow": "立即检查",
        "quick.openDetail": "打开详情",
        "quick.export": "导出支持包",
        "detail.tab.overview": "概览",
        "detail.tab.interfaces": "网络接口",
        "detail.tab.dnsRoute": "DNS 与路由",
        "detail.tab.reachability": "互联网连通性",
        "detail.tab.timeline": "时间线",
        "detail.tab.settings": "设置",
        "detail.checkNow": "立即检查",
        "detail.export": "导出支持包",
        "overview.title": "网络诊断",
        "overview.path": "网络路径",
        "overview.path.detailConstrained": "网络受限",
        "overview.path.detailNormal": "Network.framework 路径",
        "overview.activeInterfaces": "活动接口",
        "overview.dnsServers": "DNS 服务器",
        "overview.notAvailable": "未获取",
        "overview.internet": "互联网连通性",
        "overview.internet.detail": "延迟和丢包为应用层近似",
        "overview.summary": "当前说明",
        "overview.advice": "排查建议",
        "overview.empty.title": "尚未完成检查",
        "overview.empty.message": "点击“立即检查”开始只读网络诊断。",
        "interfaces.empty.title": "暂无接口数据",
        "interfaces.empty.message": "无网络时接口列表仍会显示本机只读状态。",
        "interfaces.defaultRoute": "默认路由接口",
        "interfaces.noAddress": "无 IPv4/IPv6 地址",
        "interfaces.telemetry.activeTitle": "活动网卡",
        "interfaces.telemetry.activeDetail": "物理与虚拟链路",
        "interfaces.telemetry.primaryTitle": "主干出口",
        "interfaces.telemetry.none": "无",
        "interfaces.telemetry.dualStackTitle": "协议双栈",
        "interfaces.telemetry.dualReady": "IPv4 / IPv6 双就绪",
        "interfaces.telemetry.singleReady": "单栈在线",
        "interfaces.copied": "已复制",
        "dnsRoute.section.dns": "DNS 解析器",
        "dnsRoute.source": "来源",
        "dnsRoute.noServers": "未获取到 DNS 服务器",
        "dnsRoute.searchDomains": "搜索域",
        "dnsRoute.section.routes": "默认路由",
        "dnsRoute.noRoutes": "未获取到默认路由",
        "dnsRoute.destination": "目标",
        "dnsRoute.gateway": "网关",
        "dnsRoute.interface": "接口",
        "dnsRoute.notChecked": "尚未完成检查",
        "dnsRoute.dns.telemetryTitle": "DNS 解析枢纽",
        "dnsRoute.dns.telemetryDetail": "系统解析配置",
        "dnsRoute.dns.primary": "首选 DNS",
        "dnsRoute.dns.secondary": "备用 DNS",
        "dnsRoute.dns.domainChips": "本地搜索域",
        "dnsRoute.dns.noSearchDomains": "无搜索域",
        "dnsRoute.dns.provider.google": "Google Public DNS",
        "dnsRoute.dns.provider.cloudflare": "Cloudflare 1.1.1.1",
        "dnsRoute.dns.provider.alibaba": "阿里公共 DNS",
        "dnsRoute.dns.provider.onedns": "114DNS",
        "dnsRoute.dns.provider.quad9": "Quad9 安全 DNS",
        "dnsRoute.dns.provider.local": "本地路由器 / DHCP",
        "dnsRoute.dns.provider.public": "公共递归解析器",
        "dnsRoute.route.telemetryTitle": "路由高速公路",
        "dnsRoute.route.telemetryDetail": "下一跳拓扑分流规则",
        "dnsRoute.route.defaultHeroTitle": "主干默认网关 (Default Gateway)",
        "dnsRoute.route.defaultHeroDesc": "承载非局域网全部外部互联网流量的主干出口",
        "dnsRoute.route.destination": "目标网段",
        "dnsRoute.route.nextHop": "下一跳",
        "dnsRoute.route.egressInterface": "出口网卡",
        "dnsRoute.route.filter.all": "全部",
        "dnsRoute.route.filter.default": "默认网关",
        "dnsRoute.route.filter.ipv4": "IPv4",
        "dnsRoute.route.filter.ipv6": "IPv6",
        "dnsRoute.route.copied": "已复制",
        "settings.engine.title": "诊断探针引擎",
        "settings.engine.subtitle": "并发探测公开端点网络延时与丢包",
        "settings.timeout.presetSpeedy": "极速 (1.0s)",
        "settings.timeout.presetBalanced": "稳健 (3.0s)",
        "settings.timeout.presetDeep": "深度 (5.0s)",
        "settings.endpoints.title": "并发探测公开端点",
        "settings.auto.title": "自动化巡检律动",
        "settings.auto.subtitle": "后台轻量感知链路异动与定期检查",
        "settings.auto.preset1m": "1 分钟",
        "settings.auto.preset5m": "5 分钟",
        "settings.auto.preset15m": "15 分钟",
        "settings.auto.preset1h": "1 小时",
        "settings.privacy.title": "隐私安全透明堡垒",
        "settings.privacy.subtitle": "面向 Mac App Store 沙盒标准的纯只读网络诊断实现",
        "settings.privacy.item1.title": "100% 只读诊断",
        "settings.privacy.item1.desc": "不修改系统 DNS、代理、VPN 或网络服务",
        "settings.privacy.item2.title": "零遥测与数据隐私",
        "settings.privacy.item2.desc": "所有诊断记录仅留在当前 Mac，无任何云端上报",
        "settings.privacy.item3.title": "无后台特权进程",
        "settings.privacy.item3.desc": "不安装 LaunchDaemon、特权 Helper，随关随走",
        "settings.privacy.item4.title": "智能脱敏导出",
        "settings.privacy.item4.desc": "支持包自动对 Wi-Fi SSID 与物理 MAC 脱敏",
        "settings.ecosystem.title": "推荐工具与生态",
        "reachability.successCount": "%d/%d 成功",
        "reachability.loss": "丢包近似",
        "reachability.empty.title": "暂无互联网连通性结果",
        "reachability.empty.message": "完整检查会并发探测公开 HTTPS/TCP 端点。",
        "timeline.empty.title": "暂无本地事件",
        "timeline.empty.message": "诊断记录只保存在本机。",
        "timeline.filter.all": "全部",
        "timeline.filter.pathChanges": "网络异动",
        "timeline.filter.checks": "检查记录",
        "timeline.filter.exports": "支持包导出",
        "timeline.filterEmpty.title": "该分类下暂无事件",
        "timeline.filterEmpty.message": "请切换筛选分类或执行一次检查。",
        "settings.section.probe": "互联网连通性检测",
        "settings.attempts": "每端点尝试次数",
        "settings.timeout": "超时",
        "settings.defaultEndpoints": "默认端点",
        "settings.resetEndpoints": "恢复默认端点",
        "settings.section.auto": "自动巡检",
        "settings.autoRefresh": "网络变化后自动检查",
        "settings.interval": "周期巡检间隔",
        "settings.seconds": "%d 秒",
        "settings.section.privacy": "隐私",
        "settings.privacy.local": "诊断数据只保存在本机，不会自动上传。",
        "settings.privacy.redacted": "支持包导出会脱敏 Wi-Fi SSID，不包含用户名、路径、Cookie 或密钥。",
        "settings.section.language": "语言",
        "settings.language": "界面语言",
        "settings.version": "版本",
        "settings.version.text": "版本 %@ (%@)",
        "settings.section.developer": "更多来自 Kevin Labs",
        "settings.presenterdeck.title": "PresenterDeck",
        "settings.presenterdeck.desc": "Mac 演示流程台与排练复盘 · 聚光灯、放大镜与刘海控制栏",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Mac 单应用音量独立控制 · 免驱动原生音频管理",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "轻量级 macOS 菜单栏工作台与快捷启动器",
        "common.viewInStore": "在 App Store 查看",
        "grade.checking": "检查中",
        "grade.healthy": "健康",
        "grade.warning": "警告",
        "grade.critical": "严重",
        "network.available": "可用",
        "network.unavailable": "不可用",
        "network.unknown": "未知",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "有线",
        "interface.cellular": "蜂窝",
        "interface.loopback": "回环",
        "interface.other": "其他",
        "link.up": "已连接",
        "link.down": "未连接",
        "link.unknown": "未知",
        "timeline.pathChanged": "网络变化",
        "timeline.checkStarted": "检查开始",
        "timeline.checkFinished": "检查完成",
        "timeline.exportCreated": "支持包导出",
        "timeline.diagnostic": "诊断",
        "timeline.detail.listSeparator": "、",
        "timeline.detail.pathChanged": "状态：%@ · 接口：%@",
        "timeline.detail.pathChanged.statusOnly": "状态：%@",
        "timeline.detail.checkStarted": "正在检查 %@ 个端点",
        "timeline.detail.checkFinished": "状态：%@ · 可达 %@ · 平均延迟 %@",
        "export.title": "导出网络诊断支持包",
        "export.prompt": "导出",
        "export.timeline.message": "已导出脱敏支持包：%@",
        "export.error": "导出失败：%@",
        "advice.confirmConnection.title": "确认网络已连接",
        "advice.confirmConnection.message": "先检查菜单栏 Wi-Fi 图标或网线连接。若已连接，可尝试关闭再打开 Wi-Fi，或切换到手机热点确认是否为本机网络问题。",
        "advice.enableInterface.title": "启用网络接口",
        "advice.enableInterface.message": "系统没有检测到活动接口。请打开“系统设置 > 网络”，确认 Wi-Fi 或以太网服务已启用。",
        "advice.checkDNS.title": "检查 DNS 设置",
        "advice.checkDNS.message": "当前没有读取到 DNS 服务器。可在“系统设置 > 网络 > 详细信息 > DNS”中检查，或联系网络管理员确认是否由 DHCP 下发。",
        "advice.checkRoute.title": "检查默认路由或 VPN",
        "advice.checkRoute.message": "没有获取到默认路由。若正在使用 VPN，可尝试断开后重新检查；否则请检查当前网络服务是否已获得地址和网关。",
        "advice.constrained.title": "网络处于受限状态",
        "advice.constrained.message": "系统报告网络受限，常见于手机热点、低数据模式或强制门户。请确认热点是否允许所有流量，并检查是否存在登录页面。",
        "advice.unreachable.title": "外网不可达",
        "advice.unreachable.message": "所有公开端点均探测失败。请先检查路由器、光猫和 VPN，再查看防火墙是否拦截出站连接。",
        "advice.partialUnreachable.title": "部分外网站点不可达",
        "advice.partialUnreachable.message": "部分公开端点失败，可能只是该站点被网络策略拦截或服务端异常。请优先看 Apple、Cloudflare 等主端点是否成功。",
        "advice.highLatency.title": "延迟偏高",
        "advice.highLatency.message": "P90 延迟超过 800 ms。建议暂停大流量下载或备份，优先使用 5 GHz Wi-Fi 或有线连接。",
        "advice.healthy.title": "网络状态正常",
        "advice.healthy.message": "当前没有发现需要处理的问题。若仍有网页打不开，可检查具体网站是否单独不可用。",
        "probe.error.invalidURL": "无效 URL",
        "probe.error.invalidPort": "无效端口",
        "verdict.checking": "链路探测中（网络诊断中…）",
        "verdict.notChecked": "尚未检查（点击开始诊断）",
        "verdict.optimal": "全链路畅通 · 状态极佳",
        "verdict.good": "连接稳定 · 运行正常",
        "verdict.dnsSlow": "解析异常（DNS响应超时或未配置）",
        "verdict.constrained": "带宽受限（低数据模式或策略受限）",
        "verdict.jitterLoss": "丢包抖动（部分端点探测失败）",
        "verdict.highLatency": "延迟偏高（响应时间较长）",
        "verdict.warningDefault": "局部异常（需关注网络配置）",
        "verdict.offline": "链路中断（网络已彻底断开）",
        "verdict.noInterface": "物理断开（无活动网络接口）",
        "verdict.allProbesFailed": "出口受阻（公网全线探测失败）",
        "verdict.criticalDefault": "严重异常（网络服务中断）",
        "quick.bento.latency": "延迟与质量",
        "quick.bento.interface": "活动接口",
        "quick.bento.dns": "DNS 解析",
        "quick.bento.reachability": "公网质量",
        "detail.copyCard": "复制网络诊断卡片",
        "reachability.chart.title": "公开端点延迟对比与抖动分布 (ms)",
        "reachability.chart.latency": "延迟",
        "card.header.title": "NETDOCTOR 网络诊断报告",
        "card.header.badge": "只读安全",
        "card.verdict.title": "诊断结论",
        "card.verdict.normal": "网络状态正常",
        "card.grid.path": "网络路径",
        "card.grid.path.unconstrained": "畅通",
        "card.grid.path.constrained": "受限",
        "card.grid.interfaces": "活动网络接口",
        "card.grid.interfaces.count": "%d 个",
        "card.grid.interfaces.none": "无",
        "card.grid.dns": "主 DNS 解析",
        "card.grid.dns.notConfigured": "未配置",
        "card.grid.dns.normal": "DNS 正常",
        "card.grid.dns.missing": "无 DNS",
        "card.grid.reachability": "公网连通端点",
        "card.grid.avgLatency": "平均 %.0fms",
        "settings.attempts.hint": "端点并发采样次数 (1~10)",
        "settings.timeout.hint": "单次网络请求连接上限",
        "settings.timeout.value": "%.1f 秒",
        "settings.autoRefresh.hint": "网络链路切换或重新连网时即刻触发诊断",
        "dnsRoute.routesCount": "%d 条规则",
        "common.copyTarget": "复制 %@",
        "reachability.lossFormat": "丢包 %.0f%%",
        "pipeline.node.localMac": "本机 Mac",
        "pipeline.node.gateway": "本地网关",
        "pipeline.node.dns": "DNS 解析",
        "pipeline.node.internet": "互联网",
        "gauge.scoreSuffix": "分",
        "settings.language.system": "跟随系统（自动）",
        "quick.bento.interfaces.count": "%d 个活动接口",
        "time.justNow": "刚刚",
        "time.minutesAgo": "%d 分钟前",
        "time.hoursAgo": "%d 小时前",
        "time.yesterday": "昨天 "
    ]

    private static let en: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor Diagnostics",
        "status.checking": "Checking",
        "status.notChecked": "Not checked",
        "summary.checking": "Running a local network health check.",
        "summary.notChecked": "Click Check Now to begin.",
        "summary.healthy": "Your network is healthy and internet probes are working.",
        "summary.warning": "Your network is available, but some checks need attention.",
        "summary.critical": "Your network is unavailable. Check your connection.",
        "quick.path": "Path",
        "quick.activeInterfaces": "Active Interfaces",
        "quick.dns": "DNS",
        "quick.internet": "Internet",
        "quick.notProbed": "Not probed",
        "quick.successCount": "%d/%d succeeded",
        "quick.checkNow": "Check Now",
        "quick.openDetail": "Open Details",
        "quick.export": "Export Support",
        "detail.tab.overview": "Overview",
        "detail.tab.interfaces": "Interfaces",
        "detail.tab.dnsRoute": "DNS & Route",
        "detail.tab.reachability": "Internet Connectivity",
        "detail.tab.timeline": "Timeline",
        "detail.tab.settings": "Settings",
        "detail.checkNow": "Check Now",
        "detail.export": "Export Support",
        "overview.title": "Network Health",
        "overview.path": "Network Path",
        "overview.path.detailConstrained": "Network is constrained",
        "overview.path.detailNormal": "Network.framework path",
        "overview.activeInterfaces": "Active Interfaces",
        "overview.dnsServers": "DNS Servers",
        "overview.notAvailable": "Not available",
        "overview.internet": "Internet Connectivity",
        "overview.internet.detail": "Latency and loss are app-level approximations",
        "overview.summary": "Current Summary",
        "overview.advice": "What to Check Next",
        "overview.empty.title": "Check not completed",
        "overview.empty.message": "Click Check Now to run a read-only network health check.",
        "interfaces.empty.title": "No interface data",
        "interfaces.empty.message": "The interface list still shows local read-only state when offline.",
        "interfaces.defaultRoute": "Default route interface",
        "interfaces.noAddress": "No IPv4/IPv6 address",
        "interfaces.telemetry.activeTitle": "Active Interfaces",
        "interfaces.telemetry.activeDetail": "Physical & virtual",
        "interfaces.telemetry.primaryTitle": "Primary Uplink",
        "interfaces.telemetry.none": "None",
        "interfaces.telemetry.dualStackTitle": "Dual-Stack",
        "interfaces.telemetry.dualReady": "IPv4 / IPv6 Ready",
        "interfaces.telemetry.singleReady": "Single Stack",
        "interfaces.copied": "Copied",
        "dnsRoute.section.dns": "DNS Resolver",
        "dnsRoute.source": "Source",
        "dnsRoute.noServers": "No DNS servers found",
        "dnsRoute.searchDomains": "Search Domains",
        "dnsRoute.section.routes": "Default Route",
        "dnsRoute.noRoutes": "No default route found",
        "dnsRoute.destination": "Destination",
        "dnsRoute.gateway": "Gateway",
        "dnsRoute.interface": "Interface",
        "dnsRoute.notChecked": "Check not completed",
        "dnsRoute.dns.telemetryTitle": "DNS Resolver Hub",
        "dnsRoute.dns.telemetryDetail": "System resolver topology",
        "dnsRoute.dns.primary": "Primary DNS",
        "dnsRoute.dns.secondary": "Secondary DNS",
        "dnsRoute.dns.domainChips": "Search Domains",
        "dnsRoute.dns.noSearchDomains": "No search domains",
        "dnsRoute.dns.provider.google": "Google Public DNS",
        "dnsRoute.dns.provider.cloudflare": "Cloudflare 1.1.1.1",
        "dnsRoute.dns.provider.alibaba": "AliDNS",
        "dnsRoute.dns.provider.onedns": "114DNS",
        "dnsRoute.dns.provider.quad9": "Quad9 Secure DNS",
        "dnsRoute.dns.provider.local": "Local Gateway / DHCP",
        "dnsRoute.dns.provider.public": "Public Recursive Resolver",
        "dnsRoute.route.telemetryTitle": "Routing Expressway",
        "dnsRoute.route.telemetryDetail": "Next-hop traffic forwarding",
        "dnsRoute.route.defaultHeroTitle": "Primary Default Gateway",
        "dnsRoute.route.defaultHeroDesc": "Main uplink exit routing all non-local internet traffic",
        "dnsRoute.route.destination": "Destination",
        "dnsRoute.route.nextHop": "Next-Hop",
        "dnsRoute.route.egressInterface": "Interface",
        "dnsRoute.route.filter.all": "All",
        "dnsRoute.route.filter.default": "Default",
        "dnsRoute.route.filter.ipv4": "IPv4",
        "dnsRoute.route.filter.ipv6": "IPv6",
        "dnsRoute.route.copied": "Copied",
        "settings.engine.title": "Diagnostic Engine",
        "settings.engine.subtitle": "Concurrent latency and loss probes across public endpoints",
        "settings.timeout.presetSpeedy": "Fast (1.0s)",
        "settings.timeout.presetBalanced": "Balanced (3.0s)",
        "settings.timeout.presetDeep": "Deep (5.0s)",
        "settings.endpoints.title": "Public Probe Endpoints",
        "settings.auto.title": "Auto-Pulse Telemetry",
        "settings.auto.subtitle": "Background link transition sensing and periodic checks",
        "settings.auto.preset1m": "1 min",
        "settings.auto.preset5m": "5 min",
        "settings.auto.preset15m": "15 min",
        "settings.auto.preset1h": "1 hour",
        "settings.privacy.title": "Privacy & Security Shield",
        "settings.privacy.subtitle": "Read-only network diagnostic architecture for Mac App Store",
        "settings.privacy.item1.title": "100% Read-Only Diagnostics",
        "settings.privacy.item1.desc": "Never modifies DNS, proxies, VPNs, or system network stack",
        "settings.privacy.item2.title": "Zero Telemetry & Local Privacy",
        "settings.privacy.item2.desc": "All diagnostic logs stay strictly on this Mac with no cloud reporting",
        "settings.privacy.item3.title": "No Background Daemons",
        "settings.privacy.item3.desc": "No LaunchDaemons, privileged helpers, or persistent background services",
        "settings.privacy.item4.title": "Smart Redaction on Export",
        "settings.privacy.item4.desc": "Support bundles automatically redact Wi-Fi SSIDs and hardware MAC addresses",
        "settings.ecosystem.title": "Recommended Tools & Ecosystem",
        "reachability.successCount": "%d/%d succeeded",
        "reachability.loss": "Loss",
        "reachability.empty.title": "No internet connectivity results",
        "reachability.empty.message": "A full check probes public HTTPS/TCP endpoints concurrently.",
        "timeline.empty.title": "No local events",
        "timeline.empty.message": "Diagnostic records stay on this Mac.",
        "timeline.filter.all": "All",
        "timeline.filter.pathChanges": "Changes",
        "timeline.filter.checks": "Checks",
        "timeline.filter.exports": "Exports",
        "timeline.filterEmpty.title": "No events in this category",
        "timeline.filterEmpty.message": "Switch filter or run a check.",
        "settings.section.probe": "Internet Connectivity Checks",
        "settings.attempts": "Attempts per endpoint",
        "settings.timeout": "Timeout",
        "settings.defaultEndpoints": "Default endpoints",
        "settings.resetEndpoints": "Reset default endpoints",
        "settings.section.auto": "Automatic Checks",
        "settings.autoRefresh": "Check after network changes",
        "settings.interval": "Refresh interval",
        "settings.seconds": "%d sec",
        "settings.section.privacy": "Privacy",
        "settings.privacy.local": "Diagnostic data stays on this Mac and is never uploaded automatically.",
        "settings.privacy.redacted": "Support export redacts Wi-Fi SSID and excludes usernames, paths, cookies, and keys.",
        "settings.section.language": "Language",
        "settings.language": "Interface Language",
        "settings.version": "Version",
        "settings.version.text": "Version %@ (%@)",
        "settings.section.developer": "More by Kevin Labs",
        "settings.presenterdeck.title": "PresenterDeck",
        "settings.presenterdeck.desc": "Presentation runbook & rehearsal timer for Mac with spotlight, magnifier & notch bar.",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Per-App volume control for Mac, separate meeting & music audio.",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "Lightweight macOS workspace & menu bar quick launcher.",
        "common.viewInStore": "View in App Store",
        "grade.checking": "Checking",
        "grade.healthy": "Healthy",
        "grade.warning": "Warning",
        "grade.critical": "Critical",
        "network.available": "Available",
        "network.unavailable": "Unavailable",
        "network.unknown": "Unknown",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "Wired",
        "interface.cellular": "Cellular",
        "interface.loopback": "Loopback",
        "interface.other": "Other",
        "link.up": "Connected",
        "link.down": "Disconnected",
        "link.unknown": "Unknown",
        "timeline.pathChanged": "Network changed",
        "timeline.checkStarted": "Check started",
        "timeline.checkFinished": "Check finished",
        "timeline.exportCreated": "Support export",
        "timeline.diagnostic": "Diagnostic",
        "timeline.detail.listSeparator": ", ",
        "timeline.detail.pathChanged": "Status: %@ · Interfaces: %@",
        "timeline.detail.pathChanged.statusOnly": "Status: %@",
        "timeline.detail.checkStarted": "Checking %@ endpoints",
        "timeline.detail.checkFinished": "Status: %@ · Reachable %@ · Avg latency %@",
        "export.title": "Export Network Health Support Package",
        "export.prompt": "Export",
        "export.timeline.message": "Exported redacted support package: %@",
        "export.error": "Export failed: %@",
        "advice.confirmConnection.title": "Confirm your network connection",
        "advice.confirmConnection.message": "Check the Wi-Fi icon in the menu bar or the Ethernet cable. If it is already connected, try turning Wi-Fi off and on again, or switch to a phone hotspot to see whether the issue is local.",
        "advice.enableInterface.title": "Enable a network interface",
        "advice.enableInterface.message": "No active interface was detected. Open System Settings > Network and make sure Wi-Fi or Ethernet is enabled.",
        "advice.checkDNS.title": "Check DNS settings",
        "advice.checkDNS.message": "No DNS server was found. Open System Settings > Network > Details > DNS, or ask your network administrator whether DHCP should provide one.",
        "advice.checkRoute.title": "Check the default route or VPN",
        "advice.checkRoute.message": "No default route was found. If you are using a VPN, disconnect it and check again. Otherwise, confirm that the current service received an address and gateway.",
        "advice.constrained.title": "The network is constrained",
        "advice.constrained.message": "macOS reports that this network is constrained. This often happens with phone hotspots, Low Data Mode, or captive portals.",
        "advice.unreachable.title": "The internet is unreachable",
        "advice.unreachable.message": "All public endpoints failed. Check the router, modem, and VPN first, then verify that a firewall is not blocking outbound connections.",
        "advice.partialUnreachable.title": "Some internet endpoints are unreachable",
        "advice.partialUnreachable.message": "Some public endpoints failed. This may be a blocked site or a remote service issue. Check whether Apple and Cloudflare succeeded.",
        "advice.highLatency.title": "Latency is high",
        "advice.highLatency.message": "P90 latency is above 800 ms. Pause large downloads or backups and prefer 5 GHz Wi-Fi or a wired connection.",
        "advice.healthy.title": "Your network looks healthy",
        "advice.healthy.message": "No issue was found. If a specific website still fails, check whether that site is unavailable by itself.",
        "probe.error.invalidURL": "Invalid URL",
        "probe.error.invalidPort": "Invalid port",
        "verdict.checking": "Diagnosing network links...",
        "verdict.notChecked": "Not checked (Click to diagnose)",
        "verdict.optimal": "Fully Operational · Optimal",
        "verdict.good": "Stable Connection · Normal",
        "verdict.dnsSlow": "DNS Delayed · Resolution Issue",
        "verdict.constrained": "Bandwidth Constrained · Low Data Mode",
        "verdict.jitterLoss": "Packet Loss & Jitter Detected",
        "verdict.highLatency": "High Latency · Slower Response",
        "verdict.warningDefault": "Sub-optimal · Check Configuration",
        "verdict.offline": "Link Severed · Fully Offline",
        "verdict.noInterface": "No Active Network Interface",
        "verdict.allProbesFailed": "Public Probes Failed · Route Blocked",
        "verdict.criticalDefault": "Severe Failure · Service Interrupted",
        "quick.bento.latency": "Latency & Quality",
        "quick.bento.interface": "Active Interface",
        "quick.bento.dns": "DNS Resolver",
        "quick.bento.reachability": "Internet Quality",
        "detail.copyCard": "Copy Diagnostic Card",
        "reachability.chart.title": "Public Endpoint Latency & Jitter (ms)",
        "reachability.chart.latency": "Latency",
        "card.header.title": "NETDOCTOR DIAGNOSTIC REPORT",
        "card.header.badge": "READ-ONLY SAFE",
        "card.verdict.title": "Diagnostic Verdict",
        "card.verdict.normal": "Network operating normally",
        "card.grid.path": "Network Path",
        "card.grid.path.unconstrained": "Unconstrained",
        "card.grid.path.constrained": "Constrained",
        "card.grid.interfaces": "Active Interfaces",
        "card.grid.interfaces.count": "%d Active",
        "card.grid.interfaces.none": "None",
        "card.grid.dns": "Primary DNS",
        "card.grid.dns.notConfigured": "Not configured",
        "card.grid.dns.normal": "DNS OK",
        "card.grid.dns.missing": "No DNS",
        "card.grid.reachability": "Public Endpoints",
        "card.grid.avgLatency": "Avg %.0fms",
        "settings.attempts.hint": "Concurrent probe attempts per endpoint (1–10)",
        "settings.timeout.hint": "Connection timeout cap for each request",
        "settings.timeout.value": "%.1f sec",
        "settings.autoRefresh.hint": "Trigger diagnostic check upon network changes or reconnection",
        "dnsRoute.routesCount": "%d rules",
        "common.copyTarget": "Copy %@",
        "reachability.lossFormat": "Loss %.0f%%",
        "pipeline.node.localMac": "Local Mac",
        "pipeline.node.gateway": "Local Gateway",
        "pipeline.node.dns": "DNS Resolver",
        "pipeline.node.internet": "Internet",
        "gauge.scoreSuffix": "pts",
        "settings.language.system": "System Default (Auto)",
        "quick.bento.interfaces.count": "%d Active",
        "time.justNow": "Just now",
        "time.minutesAgo": "%dm ago",
        "time.hoursAgo": "%dh ago",
        "time.yesterday": "Yesterday "
    ]

    private static let ja: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor ネットワーク診断",
        "status.checking": "診断中",
        "status.notChecked": "未診断",
        "summary.checking": "ローカルネットワーク診断を実行しています。",
        "summary.notChecked": "「今すぐ診断」をクリックして開始します。",
        "summary.healthy": "ネットワークは正常で、インターネット接続テストに合格しました。",
        "summary.warning": "ネットワークは利用可能ですが、注意が必要な項目があります。",
        "summary.critical": "ネットワークが利用できません。接続を確認してください。",
        "quick.path": "パス",
        "quick.activeInterfaces": "アクティブなインターフェース",
        "quick.dns": "DNS",
        "quick.internet": "インターネット",
        "quick.notProbed": "未検出",
        "quick.successCount": "%d/%d 成功",
        "quick.checkNow": "今すぐ診断",
        "quick.openDetail": "詳細を開く",
        "quick.export": "サポートログ出力",
        "detail.tab.overview": "概要",
        "detail.tab.interfaces": "インターフェース",
        "detail.tab.dnsRoute": "DNSとルート",
        "detail.tab.reachability": "インターネット接続性",
        "detail.tab.timeline": "タイムライン",
        "detail.tab.settings": "設定",
        "detail.checkNow": "今すぐ診断",
        "detail.export": "サポートログ出力",
        "overview.title": "ネットワーク診断",
        "overview.path": "ネットワークパス",
        "overview.path.detailConstrained": "ネットワーク制限あり",
        "overview.path.detailNormal": "Network.framework パス",
        "overview.activeInterfaces": "アクティブなインターフェース",
        "overview.dnsServers": "DNS サーバー",
        "overview.notAvailable": "取得不可",
        "overview.internet": "インターネット接続性",
        "overview.internet.detail": "遅延とパケットロスはアプリ層での近似値です",
        "overview.summary": "現在のサマリー",
        "overview.advice": "トラブルシューティングのヒント",
        "overview.empty.title": "診断未完了",
        "overview.empty.message": "「今すぐ診断」をクリックして読み取り専用の診断を開始します。",
        "interfaces.empty.title": "インターフェースデータがありません",
        "interfaces.empty.message": "オフライン時でもインターフェース一覧にローカルの状態を表示します。",
        "interfaces.defaultRoute": "デフォルトルートインターフェース",
        "interfaces.noAddress": "IPv4/IPv6 アドレスなし",
        "dnsRoute.section.dns": "DNS リゾルバー",
        "dnsRoute.source": "ソース",
        "dnsRoute.noServers": "DNSサーバーが見つかりません",
        "dnsRoute.searchDomains": "検索ドメイン",
        "dnsRoute.section.routes": "デフォルトルート",
        "dnsRoute.noRoutes": "デフォルトルートが見つかりません",
        "dnsRoute.destination": "宛先",
        "dnsRoute.gateway": "ゲートウェイ",
        "dnsRoute.interface": "インターフェース",
        "dnsRoute.notChecked": "診断未完了",
        "reachability.successCount": "%d/%d 成功",
        "reachability.loss": "パケットロス",
        "reachability.empty.title": "接続テスト結果がありません",
        "reachability.empty.message": "完全診断では公開HTTPS/TCPエンドポイントを並行テストします。",
        "timeline.empty.title": "ローカルイベントはありません",
        "timeline.empty.message": "診断ログはMac内にのみ保存されます。",
        "settings.section.probe": "インターネット接続テスト",
        "settings.attempts": "エンドポイントごとの試行回数",
        "settings.timeout": "タイムアウト",
        "settings.defaultEndpoints": "デフォルトエンドポイント",
        "settings.resetEndpoints": "デフォルトに戻す",
        "settings.section.auto": "自動診断",
        "settings.autoRefresh": "ネットワーク変更時に自動診断",
        "settings.interval": "定期診断の間隔",
        "settings.seconds": "%d 秒",
        "settings.section.privacy": "プライバシー",
        "settings.privacy.local": "診断データはMac内にのみ保存され、自動送信されることはありません。",
        "settings.privacy.redacted": "サポートログ出力時はWi-Fi SSIDが匿名化され、ユーザー名やパス、Cookie、キーは含まれません。",
        "settings.section.language": "言語",
        "settings.language": "表示言語",
        "settings.version": "バージョン",
        "settings.version.text": "バージョン %@ (%@)",
        "settings.section.developer": "Kevin Labs のその他のアプリ",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Mac向けアプリ別音量コントロール・ドライバ不要のネイティブ管理",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "軽量なmacOSメニューバー作業スペース＆クイックランチャー",
        "common.viewInStore": "App Store で見る",
        "grade.checking": "診断中",
        "grade.healthy": "良好",
        "grade.warning": "警告",
        "grade.critical": "深刻",
        "network.available": "利用可能",
        "network.unavailable": "利用不可",
        "network.unknown": "不明",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "有線",
        "interface.cellular": "モバイル通信",
        "interface.loopback": "ループバック",
        "interface.other": "その他",
        "link.up": "接続済み",
        "link.down": "未接続",
        "link.unknown": "不明",
        "timeline.pathChanged": "ネットワーク変更",
        "timeline.checkStarted": "診断開始",
        "timeline.checkFinished": "診断完了",
        "timeline.exportCreated": "サポートログ出力",
        "timeline.diagnostic": "診断",
        "timeline.detail.listSeparator": "、",
        "timeline.detail.pathChanged": "ステータス：%@ · インターフェース：%@",
        "timeline.detail.pathChanged.statusOnly": "ステータス：%@",
        "timeline.detail.checkStarted": "%@ 件のエンドポイントを確認中",
        "timeline.detail.checkFinished": "状態：%@ · 到達 %@ · 平均遅延 %@",
        "export.title": "ネットワーク診断サポートログの出力",
        "export.prompt": "出力",
        "export.timeline.message": "匿名化サポートログを出力しました：%@",
        "export.error": "出力失敗：%@",
        "advice.confirmConnection.title": "ネットワーク接続の確認",
        "advice.confirmConnection.message": "メニューバーのWi-FiアイコンまたはLANケーブルを確認してください。接続済みの場合はWi-Fiのオン/オフを切り替えるか、テザリングに接続してローカルの問題か確認してください。",
        "advice.enableInterface.title": "ネットワークインターフェースを有効化",
        "advice.enableInterface.message": "アクティブなインターフェースが見つかりません。「システム設定 > ネットワーク」でWi-Fiまたは有線LANを有効にしてください。",
        "advice.checkDNS.title": "DNS設定の確認",
        "advice.checkDNS.message": "有効なDNSサーバーが見つかりません。「システム設定 > ネットワーク > 詳細 > DNS」を確認するか、DHCPで取得できるか管理者に確認してください。",
        "advice.checkRoute.title": "デフォルトルートまたはVPNの確認",
        "advice.checkRoute.message": "デフォルトルートがありません。VPNを使用している場合は切断して再試行するか、IPとゲートウェイを取得できているか確認してください。",
        "advice.constrained.title": "ネットワークが制限されています",
        "advice.constrained.message": "macOSにより制限されたネットワークと判定されています。テザリングや低データモード、キャプティブポータルで発生します。",
        "advice.unreachable.title": "インターネットに接続できません",
        "advice.unreachable.message": "すべての公開エンドポイントへの接続に失敗しました。ルーターやモデム、VPN、ファイアウォールを確認してください。",
        "advice.partialUnreachable.title": "一部のエンドポイントに接続できません",
        "advice.partialUnreachable.message": "一部のエンドポイントで失敗しました。特定サイトのブロックや遠隔サーバー障害の可能性があります。",
        "advice.highLatency.title": "レイテンシが高めです",
        "advice.highLatency.message": "P90遅延が800msを超えています。大容量ダウンロードを一時停止し、5GHz Wi-Fiまたは有線LANの利用を推奨します。",
        "advice.healthy.title": "ネットワーク状態は正常です",
        "advice.healthy.message": "異常は検出されませんでした。特定サイトにアクセスできない場合は相手側サーバーの問題の可能性があります。",
        "probe.error.invalidURL": "無効なURL",
        "probe.error.invalidPort": "無効なポート",
        "card.header.title": "NETDOCTOR ネットワーク診断レポート",
        "card.header.badge": "読み取り専用（安全）",
        "card.verdict.title": "診断結果",
        "card.verdict.normal": "ネットワークは正常に稼働しています",
        "card.grid.path": "ネットワークパス",
        "card.grid.path.unconstrained": "制限なし",
        "card.grid.path.constrained": "制限あり",
        "card.grid.interfaces": "アクティブインターフェース",
        "card.grid.interfaces.count": "%d 件",
        "card.grid.interfaces.none": "なし",
        "card.grid.dns": "プライマリ DNS",
        "card.grid.dns.notConfigured": "未設定",
        "card.grid.dns.normal": "DNS 正常",
        "card.grid.dns.missing": "DNS なし",
        "card.grid.reachability": "公開エンドポイント",
        "card.grid.avgLatency": "平均 %.0fms",
        "settings.attempts.hint": "エンドポイントごとの同時サンプリング回数 (1〜10)",
        "settings.timeout.hint": "各リクエストのタイムアウト上限",
        "settings.timeout.value": "%.1f 秒",
        "settings.autoRefresh.hint": "ネットワーク切り替えまたは再接続時に即時自動診断",
        "dnsRoute.routesCount": "%d 件のルール",
        "common.copyTarget": "%@ をコピー",
        "reachability.lossFormat": "ロス %.0f%%",
        "pipeline.node.localMac": "この Mac",
        "pipeline.node.gateway": "ローカルゲートウェイ",
        "pipeline.node.dns": "DNS 解決",
        "pipeline.node.internet": "インターネット",
        "gauge.scoreSuffix": "点",
        "settings.language.system": "システムに従う（自動）",
        "quick.bento.interfaces.count": "%d 件のアクティブ",
        "time.justNow": "たった今",
        "time.minutesAgo": "%d分前",
        "time.hoursAgo": "%d時間前",
        "time.yesterday": "昨日 "
    ]

    private static let ko: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor 네트워크 진단",
        "status.checking": "확인 중",
        "status.notChecked": "미확인",
        "summary.checking": "로컬 네트워크 상태를 확인하고 있습니다.",
        "summary.notChecked": "'지금 확인'을 클릭하여 시작하세요.",
        "summary.healthy": "네트워크 상태가 양호하며 인터넷 연결 테스트를 통과했습니다.",
        "summary.warning": "네트워크는 사용 가능하지만 주의가 필요한 항목이 있습니다.",
        "summary.critical": "네트워크를 사용할 수 없습니다. 연결을 확인하세요.",
        "quick.path": "경로",
        "quick.activeInterfaces": "활성 인터페이스",
        "quick.dns": "DNS",
        "quick.internet": "인터넷",
        "quick.notProbed": "미측정",
        "quick.successCount": "%d/%d 성공",
        "quick.checkNow": "지금 확인",
        "quick.openDetail": "세부정보 열기",
        "quick.export": "지원 패키지 내보내기",
        "detail.tab.overview": "개요",
        "detail.tab.interfaces": "네트워크 인터페이스",
        "detail.tab.dnsRoute": "DNS 및 라우팅",
        "detail.tab.reachability": "인터넷 연결성",
        "detail.tab.timeline": "타임라인",
        "detail.tab.settings": "설정",
        "detail.checkNow": "지금 확인",
        "detail.export": "지원 패키지 내보내기",
        "overview.title": "네트워크 진단",
        "overview.path": "네트워크 경로",
        "overview.path.detailConstrained": "네트워크 제한됨",
        "overview.path.detailNormal": "Network.framework 경로",
        "overview.activeInterfaces": "활성 인터페이스",
        "overview.dnsServers": "DNS 서버",
        "overview.notAvailable": "사용 불가",
        "overview.internet": "인터넷 연결성",
        "overview.internet.detail": "지연 시간 및 손실률은 앱 레벨 추정치입니다",
        "overview.summary": "현재 요약",
        "overview.advice": "해결 권장 조치",
        "overview.empty.title": "확인 미완료",
        "overview.empty.message": "'지금 확인'을 클릭하여 읽기 전용 네트워크 진단을 시작하세요.",
        "interfaces.empty.title": "인터페이스 데이터 없음",
        "interfaces.empty.message": "오프라인 상태에서도 로컬 인터페이스 상태를 확인할 수 있습니다.",
        "interfaces.defaultRoute": "기본 라우트 인터페이스",
        "interfaces.noAddress": "IPv4/IPv6 주소 없음",
        "dnsRoute.section.dns": "DNS 확인자",
        "dnsRoute.source": "소스",
        "dnsRoute.noServers": "DNS 서버를 찾을 수 없음",
        "dnsRoute.searchDomains": "검색 도메인",
        "dnsRoute.section.routes": "기본 라우트",
        "dnsRoute.noRoutes": "기본 라우트를 찾을 수 없음",
        "dnsRoute.destination": "대상",
        "dnsRoute.gateway": "게이트웨이",
        "dnsRoute.interface": "인터페이스",
        "dnsRoute.notChecked": "확인 미완료",
        "reachability.successCount": "%d/%d 성공",
        "reachability.loss": "손실률",
        "reachability.empty.title": "인터넷 연결 결과 없음",
        "reachability.empty.message": "전체 진단 시 공용 HTTPS/TCP 엔드포인트를 동시에 테스트합니다.",
        "timeline.empty.title": "로컬 이벤트 없음",
        "timeline.empty.message": "진단 기록은 Mac에만 저장됩니다.",
        "settings.section.probe": "인터넷 연결 테스트",
        "settings.attempts": "엔드포인트당 시도 횟수",
        "settings.timeout": "시간 초과",
        "settings.defaultEndpoints": "기본 엔드포인트",
        "settings.resetEndpoints": "기본 엔드포인트로 복원",
        "settings.section.auto": "자동 점검",
        "settings.autoRefresh": "네트워크 변경 시 자동 확인",
        "settings.interval": "정기 점검 주기",
        "settings.seconds": "%d초",
        "settings.section.privacy": "개인정보 보호",
        "settings.privacy.local": "진단 데이터는 Mac에만 저장되며 자동으로 업로드되지 않습니다.",
        "settings.privacy.redacted": "지원 패키지 내보내기 시 Wi-Fi SSID가 가려지며 사용자 이름, 경로, 쿠키 또는 키는 포함되지 않습니다.",
        "settings.section.language": "언어",
        "settings.language": "인터페이스 언어",
        "settings.version": "버전",
        "settings.version.text": "버전 %@ (%@)",
        "settings.section.developer": "Kevin Labs의 다른 앱",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Mac용 앱별 독립 볼륨 조절 · 드라이버 없는 네이티브 오디오 관리",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "가벼운 macOS 메뉴 막대 작업 공간 및 퀵 런처",
        "common.viewInStore": "App Store에서 보기",
        "grade.checking": "확인 중",
        "grade.healthy": "정상",
        "grade.warning": "경고",
        "grade.critical": "치명적",
        "network.available": "사용 가능",
        "network.unavailable": "사용 불가",
        "network.unknown": "알 수 없음",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "유선",
        "interface.cellular": "셀룰러",
        "interface.loopback": "루프백",
        "interface.other": "기타",
        "link.up": "연결됨",
        "link.down": "연결 안 됨",
        "link.unknown": "알 수 없음",
        "timeline.pathChanged": "네트워크 변경",
        "timeline.checkStarted": "확인 시작",
        "timeline.checkFinished": "확인 완료",
        "timeline.exportCreated": "지원 패키지 내보냄",
        "timeline.diagnostic": "진단",
        "timeline.detail.listSeparator": ", ",
        "timeline.detail.pathChanged": "상태: %@ · 인터페이스: %@",
        "timeline.detail.pathChanged.statusOnly": "상태: %@",
        "timeline.detail.checkStarted": "엔드포인트 %@개 확인 중",
        "timeline.detail.checkFinished": "상태: %@ · 연결 %@ · 평균 지연 %@",
        "export.title": "네트워크 진단 지원 패키지 내보내기",
        "export.prompt": "내보내기",
        "export.timeline.message": "가려진 지원 패키지를 내보냈습니다: %@",
        "export.error": "내보내기 실패: %@",
        "advice.confirmConnection.title": "네트워크 연결 확인",
        "advice.confirmConnection.message": "메뉴 막대의 Wi-Fi 아이콘 또는 이더넷 케이블을 확인하세요. 연결된 경우 Wi-Fi를 껐다 켜거나 모바일 핫스팟에 연결해 보세요.",
        "advice.enableInterface.title": "네트워크 인터페이스 활성화",
        "advice.enableInterface.message": "활성 인터페이스가 감지되지 않았습니다. '시스템 설정 > 네트워크'에서 Wi-Fi 또는 이더넷이 켜져 있는지 확인하세요.",
        "advice.checkDNS.title": "DNS 설정 확인",
        "advice.checkDNS.message": "유효한 DNS 서버를 찾을 수 없습니다. '시스템 설정 > 네트워크 > 세부사항 > DNS'를 확인하거나 네트워크 관리자에게 문의하세요.",
        "advice.checkRoute.title": "기본 라우트 또는 VPN 확인",
        "advice.checkRoute.message": "기본 라우트를 찾을 수 없습니다. VPN을 사용 중이라면 연결을 끊고 다시 시도해 보세요.",
        "advice.constrained.title": "네트워크가 제한됨",
        "advice.constrained.message": "macOS에서 제한된 네트워크로 감지했습니다. 핫스팟, 저데이터 모드 또는 포털 로그인 환경일 수 있습니다.",
        "advice.unreachable.title": "인터넷에 연결할 수 없음",
        "advice.unreachable.message": "모든 공개 엔드포인트 연결에 실패했습니다. 공유기, 모뎀, VPN 및 방화벽을 확인하세요.",
        "advice.partialUnreachable.title": "일부 인터넷 엔드포인트에 연결할 수 없음",
        "advice.partialUnreachable.message": "일부 공개 엔드포인트가 실패했습니다. 특정 사이트 차단 또는 원격 서비스 문제일 수 있습니다.",
        "advice.highLatency.title": "지연 시간이 높음",
        "advice.highLatency.message": "P90 지연 시간이 800ms를 초과합니다. 대용량 다운로드를 일시 중지하고 5GHz Wi-Fi나 유선 연결을 권장합니다.",
        "advice.healthy.title": "네트워크 상태 정상",
        "advice.healthy.message": "문제가 발견되지 않았습니다. 특정 사이트가 열리지 않는다면 해당 사이트의 서비스 문제일 수 있습니다.",
        "probe.error.invalidURL": "유효하지 않은 URL",
        "probe.error.invalidPort": "유효하지 않은 포트",
        "settings.language.system": "시스템 기본값 (자동)"
    ]

    private static let de: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor Netzwerkdiagnose",
        "status.checking": "Prüfen…",
        "status.notChecked": "Nicht geprüft",
        "summary.checking": "Lokale Netzwerkprüfung wird ausgeführt.",
        "summary.notChecked": "Klicken Sie auf „Jetzt prüfen“, um zu beginnen.",
        "summary.healthy": "Netzwerkstatus ist in Ordnung, Internetverbindungstests erfolgreich.",
        "summary.warning": "Netzwerk ist verfügbar, einige Prüfungen erfordern jedoch Aufmerksamkeit.",
        "summary.critical": "Netzwerk nicht verfügbar. Bitte Verbindung überprüfen.",
        "quick.path": "Pfad",
        "quick.activeInterfaces": "Aktive Schnittstellen",
        "quick.dns": "DNS",
        "quick.internet": "Internet",
        "quick.notProbed": "Nicht getestet",
        "quick.successCount": "%d/%d erfolgreich",
        "quick.checkNow": "Jetzt prüfen",
        "quick.openDetail": "Details öffnen",
        "quick.export": "Support-Paket exportieren",
        "detail.tab.overview": "Übersicht",
        "detail.tab.interfaces": "Schnittstellen",
        "detail.tab.dnsRoute": "DNS & Routen",
        "detail.tab.reachability": "Internet-Erreichbarkeit",
        "detail.tab.timeline": "Zeitachse",
        "detail.tab.settings": "Einstellungen",
        "detail.checkNow": "Jetzt prüfen",
        "detail.export": "Support-Paket exportieren",
        "overview.title": "Netzwerkdiagnose",
        "overview.path": "Netzwerkpfad",
        "overview.path.detailConstrained": "Netzwerk eingeschränkt",
        "overview.path.detailNormal": "Network.framework-Pfad",
        "overview.activeInterfaces": "Aktive Schnittstellen",
        "overview.dnsServers": "DNS-Server",
        "overview.notAvailable": "Nicht verfügbar",
        "overview.internet": "Internet-Erreichbarkeit",
        "overview.internet.detail": "Latenz und Paketverlust sind Näherungswerte auf Anwendungsebene",
        "overview.summary": "Aktuelle Zusammenfassung",
        "overview.advice": "Fehlerbehebung",
        "overview.empty.title": "Prüfung nicht abgeschlossen",
        "overview.empty.message": "Klicken Sie auf „Jetzt prüfen“, um eine schreibgeschützte Prüfung zu starten.",
        "interfaces.empty.title": "Keine Schnittstellendaten",
        "interfaces.empty.message": "Die Schnittstellenliste zeigt auch offline den lokalen Zustand an.",
        "interfaces.defaultRoute": "Standard-Routenschnittstelle",
        "interfaces.noAddress": "Keine IPv4/IPv6-Adresse",
        "dnsRoute.section.dns": "DNS-Resolver",
        "dnsRoute.source": "Quelle",
        "dnsRoute.noServers": "Keine DNS-Server gefunden",
        "dnsRoute.searchDomains": "Suchdomänen",
        "dnsRoute.section.routes": "Standardroute",
        "dnsRoute.noRoutes": "Keine Standardroute gefunden",
        "dnsRoute.destination": "Ziel",
        "dnsRoute.gateway": "Gateway",
        "dnsRoute.interface": "Schnittstelle",
        "dnsRoute.notChecked": "Prüfung nicht abgeschlossen",
        "reachability.successCount": "%d/%d erfolgreich",
        "reachability.loss": "Paketverlust",
        "reachability.empty.title": "Keine Verbindungsergebnisse",
        "reachability.empty.message": "Eine vollständige Prüfung testet öffentliche HTTPS/TCP-Endpunkte parallel.",
        "timeline.empty.title": "Keine lokalen Ereignisse",
        "timeline.empty.message": "Diagnoseprotokolle verbleiben auf diesem Mac.",
        "settings.section.probe": "Internet-Verbindungsprüfungen",
        "settings.attempts": "Versuche pro Endpunkt",
        "settings.timeout": "Zeitüberschreitung",
        "settings.defaultEndpoints": "Standard-Endpunkte",
        "settings.resetEndpoints": "Auf Standard zurücksetzen",
        "settings.section.auto": "Automatische Prüfungen",
        "settings.autoRefresh": "Nach Netzwerkänderung prüfen",
        "settings.interval": "Aktualisierungsintervall",
        "settings.seconds": "%d Sek.",
        "settings.section.privacy": "Datenschutz",
        "settings.privacy.local": "Diagnosedaten verbleiben auf diesem Mac und werden nie automatisch hochgeladen.",
        "settings.privacy.redacted": "Der Support-Export maskiert Wi-Fi-SSIDs und schließt Benutzernamen, Pfade, Cookies und Schlüssel aus.",
        "settings.section.language": "Sprache",
        "settings.language": "Oberflächensprache",
        "settings.version": "Version",
        "settings.version.text": "Version %@ (%@)",
        "settings.section.developer": "Mehr von Kevin Labs",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "App-spezifische Lautstärkeregelung für Mac ohne zusätzliche Treiber.",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "Leichtgewichtige Menüleisten-Zentrale und Schnellstarter für macOS.",
        "common.viewInStore": "Im App Store anzeigen",
        "grade.checking": "Prüfen",
        "grade.healthy": "Fehlerfrei",
        "grade.warning": "Warnung",
        "grade.critical": "Kritisch",
        "network.available": "Verfügbar",
        "network.unavailable": "Nicht verfügbar",
        "network.unknown": "Unbekannt",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "Kabelgebunden",
        "interface.cellular": "Mobilfunk",
        "interface.loopback": "Loopback",
        "interface.other": "Andere",
        "link.up": "Verbunden",
        "link.down": "Getrennt",
        "link.unknown": "Unbekannt",
        "timeline.pathChanged": "Netzwerk geändert",
        "timeline.checkStarted": "Prüfung gestartet",
        "timeline.checkFinished": "Prüfung beendet",
        "timeline.exportCreated": "Support-Export",
        "timeline.diagnostic": "Diagnose",
        "timeline.detail.listSeparator": ", ",
        "timeline.detail.pathChanged": "Status: %@ · Schnittstellen: %@",
        "timeline.detail.pathChanged.statusOnly": "Status: %@",
        "timeline.detail.checkStarted": "%@ Endpunkte werden geprüft",
        "timeline.detail.checkFinished": "Status: %@ · Erreichbar %@ · Ø Latenz %@",
        "export.title": "Netzwerkdiagnose-Support-Paket exportieren",
        "export.prompt": "Exportieren",
        "export.timeline.message": "Bereinigtes Support-Paket exportiert: %@",
        "export.error": "Export fehlgeschlagen: %@",
        "advice.confirmConnection.title": "Netzwerkverbindung bestätigen",
        "advice.confirmConnection.message": "Überprüfen Sie das Wi-Fi-Symbol in der Menüleiste oder das Ethernet-Kabel. Schalten Sie Wi-Fi kurz aus und wieder ein oder testen Sie einen Hotspot.",
        "advice.enableInterface.title": "Netzwerkschnittstelle aktivieren",
        "advice.enableInterface.message": "Keine aktive Schnittstelle erkannt. Öffnen Sie Systemeinstellungen > Netzwerk und aktivieren Sie Wi-Fi oder Ethernet.",
        "advice.checkDNS.title": "DNS-Einstellungen prüfen",
        "advice.checkDNS.message": "Kein DNS-Server gefunden. Öffnen Sie Systemeinstellungen > Netzwerk > Details > DNS oder fragen Sie Ihren Netzwerkadministrator.",
        "advice.checkRoute.title": "Standardroute oder VPN prüfen",
        "advice.checkRoute.message": "Keine Standardroute gefunden. Trennen Sie gegebenenfalls das VPN und prüfen Sie IP-Adresse und Gateway.",
        "advice.constrained.title": "Netzwerk ist eingeschränkt",
        "advice.constrained.message": "macOS meldet ein eingeschränktes Netzwerk (häufig bei mobilen Hotspots, Datensparmodus oder Anmeldeportalen).",
        "advice.unreachable.title": "Internet nicht erreichbar",
        "advice.unreachable.message": "Alle öffentlichen Endpunkte sind fehlgeschlagen. Überprüfen Sie Router, Modem, VPN und Firewall.",
        "advice.partialUnreachable.title": "Einige Endpunkte nicht erreichbar",
        "advice.partialUnreachable.message": "Einige Endpunkte sind fehlgeschlagen. Möglicherweise liegt eine gezielte Blockierung oder eine Dienststörung vor.",
        "advice.highLatency.title": "Hohe Latenz",
        "advice.highLatency.message": "Die P90-Latenz liegt über 800 ms. Pausieren Sie große Downloads und nutzen Sie 5-GHz-WLAN oder ein Netzwerkkabel.",
        "advice.healthy.title": "Netzwerkstatus normal",
        "advice.healthy.message": "Keine Probleme festgestellt. Falls eine bestimmte Website nicht erreichbar ist, liegt der Fehler meist beim Anbieter.",
        "probe.error.invalidURL": "Ungültige URL",
        "probe.error.invalidPort": "Ungültiger Port",
        "settings.language.system": "Systemstandard (Automatisch)"
    ]

    private static let fr: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor Diagnostic réseau",
        "status.checking": "Vérification…",
        "status.notChecked": "Non vérifié",
        "summary.checking": "Vérification de l'état du réseau local en cours.",
        "summary.notChecked": "Cliquez sur « Vérifier maintenant » pour commencer.",
        "summary.healthy": "Le réseau est opérationnel, tests de connectivité Internet réussis.",
        "summary.warning": "Réseau disponible, mais certains points nécessitent votre attention.",
        "summary.critical": "Réseau indisponible. Veuillez vérifier votre connexion.",
        "quick.path": "Chemin",
        "quick.activeInterfaces": "Interfaces actives",
        "quick.dns": "DNS",
        "quick.internet": "Internet",
        "quick.notProbed": "Non testé",
        "quick.successCount": "%d/%d réussis",
        "quick.checkNow": "Vérifier",
        "quick.openDetail": "Ouvrir les détails",
        "quick.export": "Exporter le support",
        "detail.tab.overview": "Aperçu",
        "detail.tab.interfaces": "Interfaces",
        "detail.tab.dnsRoute": "DNS et routage",
        "detail.tab.reachability": "Connectivité Internet",
        "detail.tab.timeline": "Chronologie",
        "detail.tab.settings": "Réglages",
        "detail.checkNow": "Vérifier maintenant",
        "detail.export": "Exporter le support",
        "overview.title": "État du réseau",
        "overview.path": "Chemin réseau",
        "overview.path.detailConstrained": "Réseau restreint",
        "overview.path.detailNormal": "Chemin Network.framework",
        "overview.activeInterfaces": "Interfaces actives",
        "overview.dnsServers": "Serveurs DNS",
        "overview.notAvailable": "Indisponible",
        "overview.internet": "Connectivité Internet",
        "overview.internet.detail": "La latence et la perte sont des approximations au niveau applicatif",
        "overview.summary": "Résumé actuel",
        "overview.advice": "Conseils de dépannage",
        "overview.empty.title": "Vérification non effectuée",
        "overview.empty.message": "Cliquez sur « Vérifier maintenant » pour lancer une analyse en lecture seule.",
        "interfaces.empty.title": "Aucune donnée d'interface",
        "interfaces.empty.message": "La liste des interfaces affiche l'état local même hors ligne.",
        "interfaces.defaultRoute": "Interface de route par défaut",
        "interfaces.noAddress": "Aucune adresse IPv4/IPv6",
        "dnsRoute.section.dns": "Résolveur DNS",
        "dnsRoute.source": "Source",
        "dnsRoute.noServers": "Aucun serveur DNS trouvé",
        "dnsRoute.searchDomains": "Domaines de recherche",
        "dnsRoute.section.routes": "Route par défaut",
        "dnsRoute.noRoutes": "Aucune route par défaut trouvée",
        "dnsRoute.destination": "Destination",
        "dnsRoute.gateway": "Passerelle",
        "dnsRoute.interface": "Interface",
        "dnsRoute.notChecked": "Vérification non effectuée",
        "reachability.successCount": "%d/%d réussis",
        "reachability.loss": "Perte",
        "reachability.empty.title": "Aucun résultat de connectivité",
        "reachability.empty.message": "Une analyse complète sonde les points de terminaison HTTPS/TCP publics en parallèle.",
        "timeline.empty.title": "Aucun événement local",
        "timeline.empty.message": "Les historiques de diagnostic restent sur ce Mac.",
        "settings.section.probe": "Tests de connectivité Internet",
        "settings.attempts": "Tentatives par point",
        "settings.timeout": "Délai d'attente",
        "settings.defaultEndpoints": "Points par défaut",
        "settings.resetEndpoints": "Réinitialiser les points",
        "settings.section.auto": "Vérifications automatiques",
        "settings.autoRefresh": "Vérifier après modification du réseau",
        "settings.interval": "Intervalle d'actualisation",
        "settings.seconds": "%d s",
        "settings.section.privacy": "Confidentialité",
        "settings.privacy.local": "Les données de diagnostic restent sur ce Mac et ne sont jamais téléchargées automatiquement.",
        "settings.privacy.redacted": "L'exportation masque le SSID Wi-Fi et exclut les noms d'utilisateur, chemins, cookies et clés.",
        "settings.section.language": "Langue",
        "settings.language": "Langue de l'interface",
        "settings.version": "Version",
        "settings.version.text": "Version %@ (%@)",
        "settings.section.developer": "Plus par Kevin Labs",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Contrôle du volume par application pour Mac, natif et sans pilote.",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "Lanceur rapide et espace de travail léger dans la barre des menus macOS.",
        "common.viewInStore": "Voir sur l'App Store",
        "grade.checking": "Vérification",
        "grade.healthy": "Sain",
        "grade.warning": "Avertissement",
        "grade.critical": "Critique",
        "network.available": "Disponible",
        "network.unavailable": "Indisponible",
        "network.unknown": "Inconnu",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "Filaire",
        "interface.cellular": "Cellulaire",
        "interface.loopback": "Boucle locale",
        "interface.other": "Autre",
        "link.up": "Connecté",
        "link.down": "Déconnecté",
        "link.unknown": "Inconnu",
        "timeline.pathChanged": "Réseau modifié",
        "timeline.checkStarted": "Vérification démarrée",
        "timeline.checkFinished": "Vérification terminée",
        "timeline.exportCreated": "Exportation du support",
        "timeline.diagnostic": "Diagnostic",
        "timeline.detail.listSeparator": ", ",
        "timeline.detail.pathChanged": "État : %@ · Interfaces : %@",
        "timeline.detail.pathChanged.statusOnly": "État : %@",
        "timeline.detail.checkStarted": "Vérification de %@ points d'accès",
        "timeline.detail.checkFinished": "État : %@ · Accessibles %@ · Latence moy. %@",
        "export.title": "Exporter le pack d'assistance de diagnostic réseau",
        "export.prompt": "Exporter",
        "export.timeline.message": "Pack d'assistance anonymisé exporté : %@",
        "export.error": "Échec de l'exportation : %@",
        "advice.confirmConnection.title": "Confirmer la connexion réseau",
        "advice.confirmConnection.message": "Vérifiez l'icône Wi-Fi dans la barre des menus ou le câble réseau. Désactivez et réactivez le Wi-Fi, ou testez un partage de connexion mobile.",
        "advice.enableInterface.title": "Activer une interface réseau",
        "advice.enableInterface.message": "Aucune interface active détectée. Ouvrez Réglages Système > Réseau et activez le Wi-Fi ou l'Ethernet.",
        "advice.checkDNS.title": "Vérifier les réglages DNS",
        "advice.checkDNS.message": "Aucun serveur DNS trouvé. Ouvrez Réglages Système > Réseau > Détails > DNS ou contactez l'administrateur réseau.",
        "advice.checkRoute.title": "Vérifier la route par défaut ou le VPN",
        "advice.checkRoute.message": "Aucune route par défaut trouvée. Déconnectez le VPN si nécessaire et vérifiez l'adresse IP et la passerelle.",
        "advice.constrained.title": "Le réseau est restreint",
        "advice.constrained.message": "macOS signale un réseau restreint (fréquent avec le partage de connexion, le mode Faibles données ou un portail captif).",
        "advice.unreachable.title": "Internet inaccessible",
        "advice.unreachable.message": "Tous les points distants ont échoué. Vérifiez le routeur, le modem, le VPN et le pare-feu.",
        "advice.partialUnreachable.title": "Certains points sont inaccessibles",
        "advice.partialUnreachable.message": "Certains points ont échoué. Cela peut être dû à un blocage de site ou à une panne du service distant.",
        "advice.highLatency.title": "Latence élevée",
        "advice.highLatency.message": "La latence P90 dépasse 800 ms. Mettez en pause les téléchargements volumineux et privilégiez le Wi-Fi 5 GHz ou un câble Ethernet.",
        "advice.healthy.title": "Réseau en bon état",
        "advice.healthy.message": "Aucun problème détecté. Si un site spécifique échoue, il est probablement indisponible de son côté.",
        "probe.error.invalidURL": "URL non valide",
        "probe.error.invalidPort": "Port non valide",
        "settings.language.system": "Système par défaut (Auto)"
    ]

    private static let es: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor Diagnóstico de red",
        "status.checking": "Comprobando…",
        "status.notChecked": "No comprobado",
        "summary.checking": "Ejecutando un diagnóstico de red local.",
        "summary.notChecked": "Haz clic en «Comprobar ahora» para comenzar.",
        "summary.healthy": "La red funciona correctamente y las pruebas de internet son exitosas.",
        "summary.warning": "La red está disponible, pero algunos puntos requieren atención.",
        "summary.critical": "Red no disponible. Comprueba tu conexión.",
        "quick.path": "Ruta",
        "quick.activeInterfaces": "Interfaces activas",
        "quick.dns": "DNS",
        "quick.internet": "Internet",
        "quick.notProbed": "No sondeado",
        "quick.successCount": "%d/%d correctos",
        "quick.checkNow": "Comprobar ahora",
        "quick.openDetail": "Abrir detalles",
        "quick.export": "Exportar soporte",
        "detail.tab.overview": "Visión general",
        "detail.tab.interfaces": "Interfaces",
        "detail.tab.dnsRoute": "DNS y rutas",
        "detail.tab.reachability": "Conectividad a Internet",
        "detail.tab.timeline": "Línea de tiempo",
        "detail.tab.settings": "Ajustes",
        "detail.checkNow": "Comprobar ahora",
        "detail.export": "Exportar soporte",
        "overview.title": "Estado de la red",
        "overview.path": "Ruta de red",
        "overview.path.detailConstrained": "Red restringida",
        "overview.path.detailNormal": "Ruta Network.framework",
        "overview.activeInterfaces": "Interfaces activas",
        "overview.dnsServers": "Servidores DNS",
        "overview.notAvailable": "No disponible",
        "overview.internet": "Conectividad a Internet",
        "overview.internet.detail": "La latencia y la pérdida son aproximaciones a nivel de aplicación",
        "overview.summary": "Resumen actual",
        "overview.advice": "Consejos de resolución",
        "overview.empty.title": "Comprobación no realizada",
        "overview.empty.message": "Haz clic en «Comprobar ahora» para ejecutar un diagnóstico de solo lectura.",
        "interfaces.empty.title": "Sin datos de interfaz",
        "interfaces.empty.message": "La lista de interfaces muestra el estado local incluso sin conexión.",
        "interfaces.defaultRoute": "Interfaz de ruta predeterminada",
        "interfaces.noAddress": "Sin dirección IPv4/IPv6",
        "dnsRoute.section.dns": "Resolutor DNS",
        "dnsRoute.source": "Origen",
        "dnsRoute.noServers": "No se encontraron servidores DNS",
        "dnsRoute.searchDomains": "Dominios de búsqueda",
        "dnsRoute.section.routes": "Ruta predeterminada",
        "dnsRoute.noRoutes": "No se encontró ninguna ruta predeterminada",
        "dnsRoute.destination": "Destino",
        "dnsRoute.gateway": "Puerta de enlace",
        "dnsRoute.interface": "Interfaz",
        "dnsRoute.notChecked": "Comprobación no realizada",
        "reachability.successCount": "%d/%d correctos",
        "reachability.loss": "Pérdida",
        "reachability.empty.title": "Sin resultados de conectividad",
        "reachability.empty.message": "Una comprobación completa analiza puntos HTTPS/TCP públicos de forma concurrente.",
        "timeline.empty.title": "Sin eventos locales",
        "timeline.empty.message": "Los registros de diagnóstico se quedan en este Mac.",
        "settings.section.probe": "Pruebas de conectividad a Internet",
        "settings.attempts": "Intentos por endpoint",
        "settings.timeout": "Tiempo de espera",
        "settings.defaultEndpoints": "Endpoints predeterminados",
        "settings.resetEndpoints": "Restablecer endpoints",
        "settings.section.auto": "Comprobaciones automáticas",
        "settings.autoRefresh": "Comprobar tras cambios de red",
        "settings.interval": "Intervalo de actualización",
        "settings.seconds": "%d s",
        "settings.section.privacy": "Privacidad",
        "settings.privacy.local": "Los datos de diagnóstico se quedan en este Mac y nunca se envían automáticamente.",
        "settings.privacy.redacted": "La exportación anonimiza el SSID de Wi-Fi y excluye usuarios, rutas, cookies o claves.",
        "settings.section.language": "Idioma",
        "settings.language": "Idioma de la interfaz",
        "settings.version": "Versión",
        "settings.version.text": "Versión %@ (%@)",
        "settings.section.developer": "Más de Kevin Labs",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Control de volumen por aplicación para Mac, nativo y sin controladores.",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "Espacio de trabajo y lanzador rápido ligero en la barra de menús para macOS.",
        "common.viewInStore": "Ver en App Store",
        "grade.checking": "Comprobando",
        "grade.healthy": "Correcto",
        "grade.warning": "Advertencia",
        "grade.critical": "Crítico",
        "network.available": "Disponible",
        "network.unavailable": "No disponible",
        "network.unknown": "Desconocido",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "Cableada",
        "interface.cellular": "Móvil",
        "interface.loopback": "Bucle local",
        "interface.other": "Otro",
        "link.up": "Conectado",
        "link.down": "Desconectado",
        "link.unknown": "Desconocido",
        "timeline.pathChanged": "Red modificada",
        "timeline.checkStarted": "Comprobación iniciada",
        "timeline.checkFinished": "Comprobación finalizada",
        "timeline.exportCreated": "Soporte exportado",
        "timeline.diagnostic": "Diagnóstico",
        "timeline.detail.listSeparator": ", ",
        "timeline.detail.pathChanged": "Estado: %@ · Interfaces: %@",
        "timeline.detail.pathChanged.statusOnly": "Estado: %@",
        "timeline.detail.checkStarted": "Comprobando %@ puntos de acceso",
        "timeline.detail.checkFinished": "Estado: %@ · Accesibles %@ · Latencia media %@",
        "export.title": "Exportar paquete de soporte de diagnóstico de red",
        "export.prompt": "Exportar",
        "export.timeline.message": "Paquete de soporte anonimizado exportado: %@",
        "export.error": "Error al exportar: %@",
        "advice.confirmConnection.title": "Confirmar conexión de red",
        "advice.confirmConnection.message": "Comprueba el icono de Wi-Fi en la barra de menús o el cable Ethernet. Prueba a reiniciar el Wi-Fi o conéctate al punto de acceso de un móvil.",
        "advice.enableInterface.title": "Activar interfaz de red",
        "advice.enableInterface.message": "No se detectó ninguna interfaz activa. Abre Ajustes del Sistema > Red y activa Wi-Fi o Ethernet.",
        "advice.checkDNS.title": "Comprobar ajustes de DNS",
        "advice.checkDNS.message": "No se encontró ningún servidor DNS. Ve a Ajustes del Sistema > Red > Detalles > DNS o consulta con el administrador.",
        "advice.checkRoute.title": "Comprobar ruta predeterminada o VPN",
        "advice.checkRoute.message": "No se encontró ruta predeterminada. Desconecta la VPN si está activa y verifica la dirección IP y la puerta de enlace.",
        "advice.constrained.title": "La red está restringida",
        "advice.constrained.message": "macOS indica que la red está restringida (habitual en puntos de acceso móviles, modo de datos reducidos o portales cautivos).",
        "advice.unreachable.title": "Internet no accesible",
        "advice.unreachable.message": "Fallaron todos los endpoints públicos. Comprueba el router, módem, VPN y cortafuegos.",
        "advice.partialUnreachable.title": "Algunos endpoints no son accesibles",
        "advice.partialUnreachable.message": "Algunos endpoints fallaron. Puede deberse a bloqueos de red o problemas en el servicio remoto.",
        "advice.highLatency.title": "Latencia alta",
        "advice.highLatency.message": "La latencia P90 supera los 800 ms. Pausa descargas grandes y usa Wi-Fi de 5 GHz o conexión por cable.",
        "advice.healthy.title": "La red está sana",
        "advice.healthy.message": "No se encontraron problemas. Si un sitio web falla, suele deberse al propio servicio externo.",
        "probe.error.invalidURL": "URL no válida",
        "probe.error.invalidPort": "Puerto no válido",
        "settings.language.system": "Predeterminado del sistema (Auto)"
    ]

    private static let pt: [String: String] = [
        "app.name": "NetDoctor",
        "detail.window.title": "NetDoctor Diagnóstico de Rede",
        "status.checking": "Verificando…",
        "status.notChecked": "Não verificado",
        "summary.checking": "Executando verificação da rede local.",
        "summary.notChecked": "Clique em \"Verificar Agora\" para começar.",
        "summary.healthy": "A rede está saudável e os testes de internet foram bem-sucedidos.",
        "summary.warning": "A rede está disponível, mas alguns itens requerem atenção.",
        "summary.critical": "Rede indisponível. Verifique sua conexão.",
        "quick.path": "Caminho",
        "quick.activeInterfaces": "Interfaces ativas",
        "quick.dns": "DNS",
        "quick.internet": "Internet",
        "quick.notProbed": "Não testado",
        "quick.successCount": "%d/%d concluídos",
        "quick.checkNow": "Verificar Agora",
        "quick.openDetail": "Abrir Detalhes",
        "quick.export": "Exportar Suporte",
        "detail.tab.overview": "Visão Geral",
        "detail.tab.interfaces": "Interfaces",
        "detail.tab.dnsRoute": "DNS e Rotas",
        "detail.tab.reachability": "Conectividade com a Internet",
        "detail.tab.timeline": "Linha do Tempo",
        "detail.tab.settings": "Ajustes",
        "detail.checkNow": "Verificar Agora",
        "detail.export": "Exportar Suporte",
        "overview.title": "Diagnóstico da Rede",
        "overview.path": "Caminho da Rede",
        "overview.path.detailConstrained": "Rede restrita",
        "overview.path.detailNormal": "Caminho Network.framework",
        "overview.activeInterfaces": "Interfaces ativas",
        "overview.dnsServers": "Servidores DNS",
        "overview.notAvailable": "Indisponível",
        "overview.internet": "Conectividade com a Internet",
        "overview.internet.detail": "A latência e a perda são aproximações no nível do aplicativo",
        "overview.summary": "Resumo Atual",
        "overview.advice": "Dicas de Solução de Problemas",
        "overview.empty.title": "Verificação não concluída",
        "overview.empty.message": "Clique em \"Verificar Agora\" para executar uma verificação somente leitura.",
        "interfaces.empty.title": "Sem dados de interface",
        "interfaces.empty.message": "A lista de interfaces exibe o estado local mesmo offline.",
        "interfaces.defaultRoute": "Interface de rota padrão",
        "interfaces.noAddress": "Sem endereço IPv4/IPv6",
        "dnsRoute.section.dns": "Resolvedor DNS",
        "dnsRoute.source": "Origem",
        "dnsRoute.noServers": "Nenhum servidor DNS encontrado",
        "dnsRoute.searchDomains": "Domínios de busca",
        "dnsRoute.section.routes": "Rota Padrão",
        "dnsRoute.noRoutes": "Nenhuma rota padrão encontrada",
        "dnsRoute.destination": "Destino",
        "dnsRoute.gateway": "Gateway",
        "dnsRoute.interface": "Interface",
        "dnsRoute.notChecked": "Verificação não concluída",
        "reachability.successCount": "%d/%d concluídos",
        "reachability.loss": "Perda",
        "reachability.empty.title": "Sem resultados de conectividade",
        "reachability.empty.message": "Uma verificação completa analisa endpoints públicos HTTPS/TCP simultaneamente.",
        "timeline.empty.title": "Nenhum evento local",
        "timeline.empty.message": "Os registros de diagnóstico permanecem neste Mac.",
        "settings.section.probe": "Testes de Conectividade com a Internet",
        "settings.attempts": "Tentativas por endpoint",
        "settings.timeout": "Tempo limite",
        "settings.defaultEndpoints": "Endpoints padrão",
        "settings.resetEndpoints": "Restaurar endpoints padrão",
        "settings.section.auto": "Verificações Automáticas",
        "settings.autoRefresh": "Verificar após alterações de rede",
        "settings.interval": "Intervalo de atualização",
        "settings.seconds": "%d s",
        "settings.section.privacy": "Privacidade",
        "settings.privacy.local": "Os dados de diagnóstico ficam apenas neste Mac e nunca são enviados automaticamente.",
        "settings.privacy.redacted": "A exportação mascara o SSID do Wi-Fi e exclui nomes de usuário, caminhos, cookies ou chaves.",
        "settings.section.language": "Idioma",
        "settings.language": "Idioma da Interface",
        "settings.version": "Versão",
        "settings.version.text": "Versão %@ (%@)",
        "settings.section.developer": "Mais de Kevin Labs",
        "settings.volmix.title": "VolMix",
        "settings.volmix.desc": "Controle de volume por aplicativo para Mac, nativo e sem drivers.",
        "settings.ksicstudio.title": "KSIC Studio",
        "settings.ksicstudio.desc": "Iniciador rápido e espaço de trabalho leve na barra de menus para macOS.",
        "common.viewInStore": "Ver na App Store",
        "grade.checking": "Verificando",
        "grade.healthy": "Saudável",
        "grade.warning": "Aviso",
        "grade.critical": "Crítico",
        "network.available": "Disponível",
        "network.unavailable": "Indisponível",
        "network.unknown": "Desconhecido",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "Com fio",
        "interface.cellular": "Celular",
        "interface.loopback": "Loopback",
        "interface.other": "Outro",
        "link.up": "Conectado",
        "link.down": "Desconectado",
        "link.unknown": "Desconhecido",
        "timeline.pathChanged": "Rede alterada",
        "timeline.checkStarted": "Verificação iniciada",
        "timeline.checkFinished": "Verificação concluída",
        "timeline.exportCreated": "Suporte exportado",
        "timeline.diagnostic": "Diagnóstico",
        "timeline.detail.listSeparator": ", ",
        "timeline.detail.pathChanged": "Estado: %@ · Interfaces: %@",
        "timeline.detail.pathChanged.statusOnly": "Estado: %@",
        "timeline.detail.checkStarted": "Verificando %@ endpoints",
        "timeline.detail.checkFinished": "Estado: %@ · Acessíveis %@ · Latência média %@",
        "export.title": "Exportar Pacote de Suporte de Diagnóstico de Rede",
        "export.prompt": "Exportar",
        "export.timeline.message": "Pacote de suporte mascarado exportado: %@",
        "export.error": "Falha ao exportar: %@",
        "advice.confirmConnection.title": "Confirmar conexão de rede",
        "advice.confirmConnection.message": "Verifique o ícone do Wi-Fi na barra de menus ou o cabo Ethernet. Tente desativar e reativar o Wi-Fi ou use o ponto de acesso móvel.",
        "advice.enableInterface.title": "Ativar interface de rede",
        "advice.enableInterface.message": "Nenhuma interface ativa detectada. Abra Ajustes do Sistema > Rede e certifique-se de ativar o Wi-Fi ou Ethernet.",
        "advice.checkDNS.title": "Verificar configurações de DNS",
        "advice.checkDNS.message": "Nenhum servidor DNS encontrado. Vá para Ajustes do Sistema > Rede > Detalhes > DNS ou consulte o administrador de rede.",
        "advice.checkRoute.title": "Verificar rota padrão ou VPN",
        "advice.checkRoute.message": "Nenhuma rota padrão encontrada. Se estiver usando VPN, desconecte-a e verifique o endereço IP e gateway.",
        "advice.constrained.title": "A rede está restrita",
        "advice.constrained.message": "O macOS relata uma rede restrita (comum em pontos de acesso móveis, modo de dados reduzidos ou portais de login).",
        "advice.unreachable.title": "Internet inacessível",
        "advice.unreachable.message": "Todos os endpoints públicos falharam. Verifique o roteador, modem, VPN e firewall.",
        "advice.partialUnreachable.title": "Alguns endpoints estão inacessíveis",
        "advice.partialUnreachable.message": "Alguns endpoints falharam. Pode ser um bloqueio específico ou instabilidade no serviço remoto.",
        "advice.highLatency.title": "Latência alta",
        "advice.highLatency.message": "A latência P90 está acima de 800 ms. Pause downloads pesados e prefira Wi-Fi de 5 GHz ou conexão cabeada.",
        "advice.healthy.title": "Rede em bom estado",
        "advice.healthy.message": "Nenhum problema encontrado. Se um site específico falhar, provavelmente a falha é do próprio site.",
        "probe.error.invalidURL": "URL inválida",
        "probe.error.invalidPort": "Porta inválida",
        "settings.language.system": "Padrão do Sistema (Automático)"
    ]

}
