import Foundation

enum AppLanguage: String, Codable, CaseIterable, Identifiable {
    case chinese = "zh-Hans"
    case english = "en"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .chinese:
            return "简体中文"
        case .english:
            return "English"
        }
    }
}

enum L10n {
    static func string(_ key: String, language: AppLanguage) -> String {
        precondition(
            Set(zh.keys) == Set(en.keys),
            "Chinese and English localization key sets must match"
        )
        switch language {
        case .chinese:
            return zh[key] ?? en[key] ?? key
        case .english:
            return en[key] ?? zh[key] ?? key
        }
    }

    private static let zh: [String: String] = [
        "app.name": "NetworkConsole Lite",
        "detail.window.title": "网络体检",
        "status.checking": "检查中",
        "status.notChecked": "尚未检查",
        "summary.checking": "正在执行本地网络体检。",
        "summary.notChecked": "点击“立即检查”开始。",
        "summary.healthy": "网络状态正常，互联网连通性检测通过。",
        "summary.warning": "网络可用，但存在需要关注的信号。",
        "summary.critical": "网络不可用，请检查连接。",
        "quick.path": "路径",
        "quick.activeInterfaces": "活动接口",
        "quick.dns": "DNS",
        "quick.internet": "互联网",
        "quick.notProbed": "未探测",
        "quick.successCount": "%d/%d 成功",
        "quick.checkNow": "立即检查",
        "quick.openDetail": "打开详情",
        "quick.export": "导出支持包",
        "detail.tab.overview": "概览",
        "detail.tab.interfaces": "网络接口",
        "detail.tab.dnsRoute": "DNS 与路由",
        "detail.tab.reachability": "互联网连通性",
        "detail.tab.timeline": "时间线",
        "detail.tab.settings": "设置",
        "detail.checkNow": "立即检查",
        "detail.export": "导出支持包",
        "overview.title": "网络体检",
        "overview.path": "网络路径",
        "overview.path.detailConstrained": "网络受限",
        "overview.path.detailNormal": "Network.framework 路径",
        "overview.activeInterfaces": "活动接口",
        "overview.dnsServers": "DNS 服务器",
        "overview.notAvailable": "未获取",
        "overview.internet": "互联网连通性",
        "overview.internet.detail": "延迟和丢包为应用层近似",
        "overview.summary": "当前说明",
        "overview.advice": "排查建议",
        "overview.empty.title": "尚未完成检查",
        "overview.empty.message": "点击“立即检查”开始只读网络体检。",
        "interfaces.empty.title": "暂无接口数据",
        "interfaces.empty.message": "无网络时接口列表仍会显示本机只读状态。",
        "interfaces.defaultRoute": "默认路由接口",
        "interfaces.noAddress": "无 IPv4/IPv6 地址",
        "dnsRoute.section.dns": "DNS 解析器",
        "dnsRoute.source": "来源",
        "dnsRoute.noServers": "未获取到 DNS 服务器",
        "dnsRoute.searchDomains": "搜索域",
        "dnsRoute.section.routes": "默认路由",
        "dnsRoute.noRoutes": "未获取到默认路由",
        "dnsRoute.destination": "目标",
        "dnsRoute.gateway": "网关",
        "dnsRoute.interface": "接口",
        "dnsRoute.notChecked": "尚未完成检查",
        "reachability.successCount": "%d/%d 成功",
        "reachability.loss": "丢包近似",
        "reachability.empty.title": "暂无互联网连通性结果",
        "reachability.empty.message": "完整检查会并发探测公开 HTTPS/TCP 端点。",
        "timeline.empty.title": "暂无本地事件",
        "timeline.empty.message": "诊断记录只保存在本机。",
        "settings.section.probe": "互联网连通性检测",
        "settings.attempts": "每端点尝试次数",
        "settings.timeout": "超时",
        "settings.defaultEndpoints": "默认端点",
        "settings.resetEndpoints": "恢复默认端点",
        "settings.section.auto": "自动巡检",
        "settings.autoRefresh": "网络变化后自动检查",
        "settings.interval": "周期巡检间隔",
        "settings.seconds": "%d 秒",
        "settings.section.privacy": "隐私",
        "settings.privacy.local": "诊断数据只保存在本机，不会自动上传。",
        "settings.privacy.redacted": "支持包导出会脱敏 Wi-Fi SSID，不包含用户名、路径、Cookie 或密钥。",
        "settings.section.language": "语言",
        "settings.language": "界面语言",
        "settings.version": "版本",
        "settings.version.text": "版本 %@ (%@)",
        "grade.checking": "检查中",
        "grade.healthy": "健康",
        "grade.warning": "警告",
        "grade.critical": "严重",
        "network.available": "可用",
        "network.unavailable": "不可用",
        "network.unknown": "未知",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "有线",
        "interface.cellular": "蜂窝",
        "interface.loopback": "回环",
        "interface.other": "其他",
        "link.up": "已连接",
        "link.down": "未连接",
        "link.unknown": "未知",
        "timeline.pathChanged": "网络变化",
        "timeline.checkStarted": "检查开始",
        "timeline.checkFinished": "检查完成",
        "timeline.exportCreated": "支持包导出",
        "timeline.diagnostic": "诊断",
        "export.title": "导出网络体检支持包",
        "export.prompt": "导出",
        "export.timeline.message": "已导出脱敏支持包：%@",
        "export.error": "导出失败：%@"
    ]

    private static let en: [String: String] = [
        "app.name": "NetworkConsole Lite",
        "detail.window.title": "Network Health",
        "status.checking": "Checking",
        "status.notChecked": "Not checked",
        "summary.checking": "Running a local network health check.",
        "summary.notChecked": "Click Check Now to begin.",
        "summary.healthy": "Your network is healthy and internet probes are working.",
        "summary.warning": "Your network is available, but some checks need attention.",
        "summary.critical": "Your network is unavailable. Check your connection.",
        "quick.path": "Path",
        "quick.activeInterfaces": "Active Interfaces",
        "quick.dns": "DNS",
        "quick.internet": "Internet",
        "quick.notProbed": "Not probed",
        "quick.successCount": "%d/%d succeeded",
        "quick.checkNow": "Check Now",
        "quick.openDetail": "Open Details",
        "quick.export": "Export Support",
        "detail.tab.overview": "Overview",
        "detail.tab.interfaces": "Interfaces",
        "detail.tab.dnsRoute": "DNS & Route",
        "detail.tab.reachability": "Internet Connectivity",
        "detail.tab.timeline": "Timeline",
        "detail.tab.settings": "Settings",
        "detail.checkNow": "Check Now",
        "detail.export": "Export Support",
        "overview.title": "Network Health",
        "overview.path": "Network Path",
        "overview.path.detailConstrained": "Network is constrained",
        "overview.path.detailNormal": "Network.framework path",
        "overview.activeInterfaces": "Active Interfaces",
        "overview.dnsServers": "DNS Servers",
        "overview.notAvailable": "Not available",
        "overview.internet": "Internet Connectivity",
        "overview.internet.detail": "Latency and loss are app-level approximations",
        "overview.summary": "Current Summary",
        "overview.advice": "What to Check Next",
        "overview.empty.title": "Check not completed",
        "overview.empty.message": "Click Check Now to run a read-only network health check.",
        "interfaces.empty.title": "No interface data",
        "interfaces.empty.message": "The interface list still shows local read-only state when offline.",
        "interfaces.defaultRoute": "Default route interface",
        "interfaces.noAddress": "No IPv4/IPv6 address",
        "dnsRoute.section.dns": "DNS Resolver",
        "dnsRoute.source": "Source",
        "dnsRoute.noServers": "No DNS servers found",
        "dnsRoute.searchDomains": "Search Domains",
        "dnsRoute.section.routes": "Default Route",
        "dnsRoute.noRoutes": "No default route found",
        "dnsRoute.destination": "Destination",
        "dnsRoute.gateway": "Gateway",
        "dnsRoute.interface": "Interface",
        "dnsRoute.notChecked": "Check not completed",
        "reachability.successCount": "%d/%d succeeded",
        "reachability.loss": "Loss",
        "reachability.empty.title": "No internet connectivity results",
        "reachability.empty.message": "A full check probes public HTTPS/TCP endpoints concurrently.",
        "timeline.empty.title": "No local events",
        "timeline.empty.message": "Diagnostic records stay on this Mac.",
        "settings.section.probe": "Internet Connectivity Checks",
        "settings.attempts": "Attempts per endpoint",
        "settings.timeout": "Timeout",
        "settings.defaultEndpoints": "Default endpoints",
        "settings.resetEndpoints": "Reset default endpoints",
        "settings.section.auto": "Automatic Checks",
        "settings.autoRefresh": "Check after network changes",
        "settings.interval": "Refresh interval",
        "settings.seconds": "%d sec",
        "settings.section.privacy": "Privacy",
        "settings.privacy.local": "Diagnostic data stays on this Mac and is never uploaded automatically.",
        "settings.privacy.redacted": "Support export redacts Wi-Fi SSID and excludes usernames, paths, cookies, and keys.",
        "settings.section.language": "Language",
        "settings.language": "Interface Language",
        "settings.version": "Version",
        "settings.version.text": "Version %@ (%@)",
        "grade.checking": "Checking",
        "grade.healthy": "Healthy",
        "grade.warning": "Warning",
        "grade.critical": "Critical",
        "network.available": "Available",
        "network.unavailable": "Unavailable",
        "network.unknown": "Unknown",
        "interface.wifi": "Wi-Fi",
        "interface.wired": "Wired",
        "interface.cellular": "Cellular",
        "interface.loopback": "Loopback",
        "interface.other": "Other",
        "link.up": "Connected",
        "link.down": "Disconnected",
        "link.unknown": "Unknown",
        "timeline.pathChanged": "Network changed",
        "timeline.checkStarted": "Check started",
        "timeline.checkFinished": "Check finished",
        "timeline.exportCreated": "Support export",
        "timeline.diagnostic": "Diagnostic",
        "export.title": "Export Network Health Support Package",
        "export.prompt": "Export",
        "export.timeline.message": "Exported redacted support package: %@",
        "export.error": "Export failed: %@"
    ]
}
